In [3]:
import tensorflow as tf 

# GRAPH

In [4]:
a = tf.constant(10)
b = tf.constant(20) 

In [5]:
c= a+b

In [6]:
with tf.Session() as sess :
    result = sess.run(c)

In [7]:
print(result)  

30


### Let's See about the Default Graph

In [8]:
print(tf.get_default_graph())

In [9]:
g = tf.Graph() 

Now setting a graph as defualt graph

In [10]:
graph1 = tf.get_default_graph()

In [11]:
print(graph1)

Here we can see that both the location of default_graph and graph1 is same 

In [12]:
graph1 is tf.get_default_graph() 

True

In [13]:
g is tf.get_default_graph()

False

Now we'll set g as default only for that notebook 

In [14]:
with g.as_default():
    print(g is tf.get_default_graph())

True


# VARIABLE

In [15]:
temp = tf.random_normal([3,3] , mean  = 0 , stddev = 1) 

In [16]:
var = tf.Variable(initial_value = temp)

In [19]:
with tf.Session() as sess :
    print(var)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32_ref>


#### INITALIZING ALL GLOBAL VARIABLES

In [24]:
init = tf.global_variables_initializer()  

In [27]:
with tf.Session() as sess :
    init.run()
    print(var.eval())

[[-0.4281579   1.7910084   0.28665075]
 [-0.20566832  1.1796046   0.14174873]
 [ 1.2104119   0.70587426 -0.19732836]]


# PLACEHOLDER

In [28]:
place = tf.placeholder(tf.float32 , shape=(5,5))