In [4]:
import tensorflow as tf 

In [5]:
#Printing the version of TensorFlow 

print(tf.__version__)

1.15.0


# Let's create a Tensor

In [6]:
hello = tf.constant("Hello") 

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


Here we can see that on printing hello it is printing the tensor showing that hello is a tensor object

In [8]:
world = tf.constant("world") 


In [9]:
final = hello + world 

In [10]:
print(final) 

Tensor("add:0", shape=(), dtype=string)


Let's see the Type of hello and final

In [11]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [12]:
type(final)

tensorflow.python.framework.ops.Tensor

## Printing and Evaluating tensors 

In [13]:
with tf.Session() as sess :
    result = tf.add(hello,world) 

In [14]:
result

<tf.Tensor 'Add_1:0' shape=() dtype=string>

Advantage of using with tf.Session() is that we don't have to close the sess as sess.close()

In [15]:
with tf.Session() as sess :
    result = sess.run(hello + world) 

In [16]:
result

b'Helloworld'

## Let's See some Basic TF operations 

In [17]:
c = tf.constant(10) 

In [18]:
zeros = tf.zeros([4,4] ,tf.int32)

In [19]:
fill = tf.fill([4,4],5) 

In [20]:
ones = tf.ones([4,4] , tf.int32)

In [21]:
random = tf.random_normal([3,3] , stddev=1 , mean=0 ,dtype =  tf.float32 , seed = 101 )

### Now we will create a list which will contain all this tensors 

In [22]:
list = [c,zeros,fill,ones,random] 

In [24]:
with tf.Session() as sess :
    for val in list :
        print(val.eval()) 
        print("\n")

10


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[-2.3159974  -0.07912122 -0.8998717 ]
 [ 0.31664512 -1.1119006   1.3949379 ]
 [ 0.4992896  -1.461813   -0.7174765 ]]




## Matrix Multiplication

In [25]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [26]:
b = tf.constant([[10],[100]])

In [27]:
result = tf.matmul(a,b)

In [29]:
with tf.Session() as sess :
    print(result.eval())

[[210]
 [430]]
